// Source-text translator for the Mini App: Uzbek text is the key, EN/RU are looked up here.
export type TrLang = "uz" | "en" | "ru";

export function currentLang(): TrLang {
  try {
    const l = typeof window !== "undefined" ? window.localStorage.getItem("kh-lang") : null;
    return l === "en" || l === "ru" ? l : "uz";
  } catch {
    return "uz";
  }
}

const D: Record<string, [string, string]> = {
  " (16 yoshgacha)": [" (under 16)", " (до 16 лет)"],
  "AI yozmoqda...": ["AI is typing...", "AI печатает..."],
  "Ariza ekspertizaga qabul qilindi.": ["The application was accepted for review.", "Заявка принята на экспертизу."],
  "Ariza sizning roziligingizni kutmoqda. Rozilik bergach, ariza ko'rib chiqishga yuboriladi.": ["The application awaits your consent. After you approve, it will be sent for review.", "Заявка ждёт вашего согласия. После одобрения она будет отправлена на рассмотрение."],
  "Arizalarim": ["My applications", "Мои заявки"],
  "Bog'langan farzand yo'q. Farzandingiz botda maxfiy raqamni kiritishi kerak.": ["No linked child. Your child must enter the secret code in the bot.", "Нет привязанного ребёнка. Ребёнок должен ввести секретный код в боте."],
  "Boshlash": ["Start", "Начать"],
  "Bu bo'limda hozircha dars yo'q.": ["No lessons in this section yet.", "В этом разделе пока нет уроков."],
  "Bu sahifa Telegram bot ichida ochilishi kerak. @kelajakhubbot ga kiring va «KelajakHub» tugmasini bosing.": ["This page must be opened inside the Telegram bot. Open @kelajakhubbot and tap «KelajakHub».", "Эту страницу нужно открыть в Telegram-боте. Откройте @kelajakhubbot и нажмите «KelajakHub»."],
  "Chat tarixi 30 kundan keyin avtomatik o'chiriladi. Patent tarixi hech qachon o'chmaydi.": ["Chat history is deleted after 30 days. Patent history is never deleted.", "История чата удаляется через 30 дней. История патентов не удаляется никогда."],
  "Davlat yig'imi (Intellektual mulk agentligi):": ["State fee (IP Agency):", "Госпошлина (Агентство ИС):"],
  "Farzand loyihalari": ["Child's projects", "Проекты ребёнка"],
  "Farzand patentlari": ["Child's patents", "Патенты ребёнка"],
  "Farzand uchun maxfiy raqam": ["Secret code for your child", "Секретный код для ребёнка"],
  "Farzandlar": ["Children", "Дети"],
  "G'oya, patent va prototip bo'yicha darhol maslahat": ["Instant advice on ideas, patents and prototypes", "Мгновенные советы по идеям, патентам и прототипам"],
  "Guruh faoliyatini kuzatish →": ["Watch group activity →", "Следить за группой →"],
  "Guruhga qo'shilish →": ["Join the group →", "Вступить в группу →"],
  "Holat:": ["Status:", "Статус:"],
  "Hozircha ariza yo'q.": ["No applications yet.", "Пока нет заявок."],
  "Hozircha investitsiya taklifi yo'q. Loyihangizni to'liq to'ldirsangiz, investorlar ko'radi.": ["No investment offers yet. Complete your project so investors can see it.", "Пока нет инвестиционных предложений. Заполните проект полностью — инвесторы его увидят."],
  "Hozircha ixtiro yo'q. Botdagi «Ixtironi patentlash markaziga yuborish» tugmasidan foydalaning.": ["No inventions yet. Use the patent button in the bot.", "Пока нет изобретений. Используйте кнопку патентования в боте."],
  "Hozircha jamoa e'lonlari yo'q.": ["No team posts yet.", "Пока нет объявлений о команде."],
  "Hozircha loyiha yo'q — yuqoridagi formadan qo'shing.": ["No projects yet — add one with the form above.", "Пока нет проектов — добавьте через форму выше."],
  "Hozircha loyiha yo'q.": ["No projects yet.", "Пока нет проектов."],
  "Hozircha mentor ro'yxatdan o'tmagan.": ["No mentors registered yet.", "Пока нет зарегистрированных менторов."],
  "Hozircha mentor yo'q.": ["No mentors yet.", "Пока нет менторов."],
  "Hozircha sizga ulangan loyiha yo'q.": ["No projects linked to you yet.", "Пока нет привязанных к вам проектов."],
  "Hozircha suhbat yo'q.": ["No chats yet.", "Пока нет чатов."],
  "Hozircha taklif yubormadingiz.": ["You haven't sent any offers yet.", "Вы ещё не отправляли предложений."],
  "Investitsiya maqsadi": ["Funding goal", "Цель инвестиций"],
  "Investitsiya taklif qilish": ["Make an investment offer", "Предложить инвестицию"],
  "Investor:": ["Investor:", "Инвестор:"],
  "Ixtiro nomi": ["Invention title", "Название изобретения"],
  "Ixtiro nomi va tavsifini to'liqroq yozing (tavsif kamida 20 belgi).": ["Fill in the title and description (at least 20 characters).", "Заполните название и описание (не менее 20 символов)."],
  "Ixtiro tavsifi (mohiyati, yangiligi, qo'llanishi)": ["Description (essence, novelty, use)", "Описание (суть, новизна, применение)"],
  "Ixtirochi:": ["Inventor:", "Изобретатель:"],
  "Jamoa izlayapman": ["Looking for a team", "Ищу команду"],
  "Jamoa izlayotgan loyihalar": ["Projects looking for a team", "Проекты ищут команду"],
  "Jamoaga a'zo kerak.": ["Team members needed.", "Нужны участники команды."],
  "Javobingiz yoki savolingiz...": ["Your answer or question...", "Ваш ответ или вопрос..."],
  "KelajakHub xizmat haqi (": ["KelajakHub service fee (", "Комиссия KelajakHub ("],
  "Kim kerak?": ["Who do you need?", "Кто нужен?"],
  "Kod, formula, tajriba yoki ixtiro g'oyangizni yozing — AI uni tahlil qilib, xatolarni va yaxshilash yo'llarini ko'rsatadi.": ["Write code, a formula, an experiment or an idea — AI will analyze it and show mistakes and improvements.", "Напишите код, формулу, опыт или идею — AI проанализирует и покажет ошибки и улучшения."],
  "Logo havolasi": ["Logo link", "Ссылка на логотип"],
  "Loyiha guruhiga kirish →": ["Open project group →", "Открыть группу проекта →"],
  "Loyiha nomi va tavsifini to'liq kiriting.": ["Enter the project title and description.", "Введите название и описание проекта."],
  "Loyiha saqlandi": ["Project saved", "Проект сохранён"],
  "Loyiha yo'q.": ["No projects.", "Нет проектов."],
  "Loyihalar": ["Projects", "Проекты"],
  "Loyihamga kelgan takliflar": ["Offers for my project", "Предложения по моему проекту"],
  "Loyihani tahrirlash": ["Edit project", "Редактировать проект"],
  "Maqsad:": ["Goal:", "Цель:"],
  "Mening loyihalarim": ["My projects", "Мои проекты"],
  "Mening takliflarim": ["My offers", "Мои предложения"],
  "Mentor": ["Mentor", "Ментор"],
  "Mentor profili": ["Mentor profile", "Профиль ментора"],
  "Mentor ulash": ["Add mentor", "Подключить ментора"],
  "Mentorga so'rov yuborildi": ["Request sent to mentor", "Запрос отправлен ментору"],
  "Mentorlar": ["Mentors", "Менторы"],
  "Mentorlik loyihalari": ["Mentored projects", "Проекты под менторством"],
  "Muallif:": ["Author:", "Автор:"],
  "Muhr": ["Seal", "Печать"],
  "Natija": ["Result", "Результат"],
  "Nomi": ["Title", "Название"],
  "O'zbek tilidagi bepul video darslar. Darsdan so'ng AI bilimingizni tekshiradi.": ["Free video lessons in Uzbek. After a lesson, AI checks your knowledge.", "Бесплатные видеоуроки на узбекском. После урока AI проверит знания."],
  "Ota-ona roziligi kutilmoqda.": ["Waiting for parent consent.", "Ожидается согласие родителя."],
  "Patent portfeli": ["Patent portfolio", "Патентный портфель"],
  "Patent to'lovi": ["Patent fee", "Патентная пошлина"],
  "Patent yo'q.": ["No patents.", "Нет патентов."],
  "Patentlar": ["Patents", "Патенты"],
  "Profil saqlandi": ["Profile saved", "Профиль сохранён"],
  "Qisqa ma'lumot": ["Short bio", "Кратко о себе"],
  "Qonuniy patent arizasi uchun OneID orqali shaxsingizni tasdiqlashingiz shart.": ["A legal patent application requires identity verification via OneID.", "Для патентной заявки нужно подтвердить личность через OneID."],
  "Rad etildi": ["Rejected", "Отклонено"],
  "Rad etish": ["Reject", "Отклонить"],
  "Raqamli muhr olib, arizani topshirish": ["Get a digital seal and submit", "Получить цифровую печать и подать"],
  "Rozilik": ["Approve", "Согласие"],
  "Rozilik berildi": ["Approved", "Согласие дано"],
  "Rozilik kutayotgan investitsiyalar": ["Investments awaiting consent", "Инвестиции ждут согласия"],
  "Rozilik kutayotgan taklif yo'q.": ["No offers awaiting consent.", "Нет предложений, ожидающих согласия."],
  "Saqlanmoqda...": ["Saving...", "Сохранение..."],
  "Saqlash": ["Save", "Сохранить"],
  "Savol tayyorlanmoqda...": ["Preparing a question...", "Готовлю вопрос..."],
  "Shaxsni tasdiqlash talab qiladi": ["Identity verification required", "Требуется подтверждение личности"],
  "So'rov bajarilmadi": ["Request failed", "Запрос не выполнен"],
  "Suhbatlar": ["Chats", "Чаты"],
  "Suhbatni boshlang.": ["Start the conversation.", "Начните разговор."],
  "Summa": ["Amount", "Сумма"],
  "Summani kiriting.": ["Enter the amount.", "Введите сумму."],
  "Tahlil qilinmoqda...": ["Analyzing...", "Анализ..."],
  "Tahrirlash": ["Edit", "Изменить"],
  "Taklif yuborildi": ["Offer sent", "Предложение отправлено"],
  "Taklif yuborildi — ota-ona roziligi kutilmoqda": ["Offer sent — awaiting parent consent", "Предложение отправлено — ждём согласия родителя"],
  "Tavsif": ["Description", "Описание"],
  "Telegram guruh havolasi": ["Telegram group link", "Ссылка на Telegram-группу"],
  "To'lov ariza ekspertizadan o'tgach hisoblanadi. Davlat yig'imi to'liq davlat budjetiga o'tadi.": ["Payment is calculated after review. The state fee goes fully to the state budget.", "Оплата рассчитывается после экспертизы. Госпошлина полностью идёт в бюджет."],
  "Umumiy:": ["Total:", "Итого:"],
  "Xabar": ["Message", "Сообщение"],
  "Xabar yozing...": ["Write a message...", "Напишите сообщение..."],
  "Xizmat haqi (masalan: 150 000 so'm / oy)": ["Fee (e.g. 150 000 UZS / month)", "Стоимость (напр. 150 000 сум / мес)"],
  "Xizmat haqi ixtirochilarga mentor tanlashda ko'rinadi. To'lov mentor va ixtirochi o'rtasida kelishiladi.": ["Your fee is shown to inventors. Payment is agreed between mentor and inventor.", "Стоимость видна изобретателям. Оплата согласуется между ментором и изобретателем."],
  "Yangi loyiha": ["New project", "Новый проект"],
  "Yangi patent arizasi": ["New patent application", "Новая патентная заявка"],
  "Yo'nalish (masalan: IT, robototexnika)": ["Field (e.g. IT, robotics)", "Направление (напр. IT, робототехника)"],
  "YouTube kanali:": ["YouTube channel:", "YouTube-канал:"],
  "YouTube'da ochish ↗": ["Open on YouTube ↗", "Открыть в YouTube ↗"],
  "Yuborilmoqda...": ["Sending...", "Отправка..."],
  "Yuborish": ["Send", "Отправить"],
  "Yuklanmoqda...": ["Loading...", "Загрузка..."],
  "raqam yo'q": ["no phone", "нет номера"],
  "so'm": ["UZS", "сум"],
  "· holat:": ["· status:", "· статус:"],
  "· muhr:": ["· seal:", "· печать:"],
  "‹ Darslar": ["‹ Lessons", "‹ Уроки"],
  "← Suhbatlar": ["← Chats", "← Чаты"],
  "⏳ Ixtironi patentlash xizmati hozircha ishga tushmagan. Tez orada ochiladi.": ["⏳ The patent service is not live yet. Coming soon.", "⏳ Сервис патентования пока не запущен. Скоро откроется."],
  "▶ Tahlil qilish": ["▶ Analyze", "▶ Анализировать"],
  "✅ Darsni ko'rib bo'ldim — AI bilan savol-javob": ["✅ I watched it — quiz with AI", "✅ Я посмотрел — вопросы с AI"],
  "✅ Rozilik beraman": ["✅ I approve", "✅ Даю согласие"],
  "🏛 OneID orqali tasdiqlash": ["🏛 Verify via OneID", "🏛 Подтвердить через OneID"],
  "🤖 AI Mentor": ["🤖 AI Mentor", "🤖 AI Ментор"],
  "🤖 AI savol-javob": ["🤖 AI quiz", "🤖 AI вопросы"],
  "🧪 Laboratoriya": ["🧪 Laboratory", "🧪 Лаборатория"],
  "tasdiqlangan": ["verified", "подтверждён"],
  "tasdiqlanmagan": ["not verified", "не подтверждён"],
  "ota-ona roziligi kutilmoqda": ["awaiting parent consent", "ждёт согласия родителя"],
  "rad etilgan": ["rejected", "отклонено"],
  // tabs, roles, categories
  "Bosh": ["Home", "Главная"],
  "Patent": ["Patent", "Патент"],
  "Investitsiya": ["Invest", "Инвестиции"],
  "Nazorat": ["Control", "Контроль"],
  "Profil": ["Profile", "Профиль"],
  "Darslar": ["Lessons", "Уроки"],
  "Lab": ["Lab", "Лаб"],
  "Yosh ixtirochi": ["Young inventor", "Юный изобретатель"],
  "Katta ixtirochi": ["Adult inventor", "Взрослый изобретатель"],
  "Ota-ona": ["Parent", "Родитель"],
  "Investor": ["Investor", "Инвестор"],
  "Dasturlash": ["Programming", "Программирование"],
  "Grafik dizayn": ["Graphic design", "Графический дизайн"],
  "Startup": ["Startup", "Стартап"],
  // server messages
  "initData tasdiqlanmadi": ["Telegram session could not be verified. Close and reopen the Mini App.", "Сессия Telegram не подтверждена. Закройте и откройте Mini App снова."],
  "Avval botda ro'yxatdan o'ting": ["Register in the bot first", "Сначала зарегистрируйтесь в боте"],
  "Ruxsat yo'q": ["Access denied", "Нет доступа"],
  "Loyiha topilmadi": ["Project not found", "Проект не найден"],
  "Suhbat topilmadi": ["Chat not found", "Чат не найден"],
  "Foydalanuvchi topilmadi": ["User not found", "Пользователь не найден"],
  "Faqat investorlar investitsiya taklif qiladi": ["Only investors can make offers", "Только инвесторы могут предлагать инвестиции"],
  "Faqat ota-onalar uchun": ["Parents only", "Только для родителей"],
  "Faqat mentorlar uchun": ["Mentors only", "Только для менторов"],
};

export function tr(text: string | null | undefined): string {
  if (text == null) return "";
  const lang = currentLang();
  if (lang === "uz") return text;
  const hit = D[text];
  return hit ? hit[lang === "en" ? 0 : 1] : text;
}
