/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiPublicMiniappLabRouteImport } from './routes/api/public/miniapp/lab'
import { Route as ApiPublicMiniappProfileRouteImport } from './routes/api/public/miniapp/profile'
import { Route as ApiPublicMiniappRpcRouteImport } from './routes/api/public/miniapp/rpc'
import { Route as ApiPublicOneidStartRouteImport } from './routes/api/public/oneid/start'
import { Route as ApiPublicTelegramSetupRouteImport } from './routes/api/public/telegram/setup'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMiniappLabRoute = ApiPublicMiniappLabRouteImport.update({
  id: '/api/public/miniapp/lab',
  path: '/api/public/miniapp/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMiniappProfileRoute = ApiPublicMiniappProfileRouteImport.update({
  id: '/api/public/miniapp/profile',
  path: '/api/public/miniapp/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMiniappRpcRoute = ApiPublicMiniappRpcRouteImport.update({
  id: '/api/public/miniapp/rpc',
  path: '/api/public/miniapp/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOneidStartRoute = ApiPublicOneidStartRouteImport.update({
  id: '/api/public/oneid/start',
  path: '/api/public/oneid/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramSetupRoute = ApiPublicTelegramSetupRouteImport.update({
  id: '/api/public/telegram/setup',
  path: '/api/public/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/api/public/miniapp/lab': typeof ApiPublicMiniappLabRoute
  '/api/public/miniapp/profile': typeof ApiPublicMiniappProfileRoute
  '/api/public/miniapp/rpc': typeof ApiPublicMiniappRpcRoute
  '/api/public/oneid/start': typeof ApiPublicOneidStartRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/api/public/miniapp/lab': typeof ApiPublicMiniappLabRoute
  '/api/public/miniapp/profile': typeof ApiPublicMiniappProfileRoute
  '/api/public/miniapp/rpc': typeof ApiPublicMiniappRpcRoute
  '/api/public/oneid/start': typeof ApiPublicOneidStartRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/api/public/miniapp/lab': typeof ApiPublicMiniappLabRoute
  '/api/public/miniapp/profile': typeof ApiPublicMiniappProfileRoute
  '/api/public/miniapp/rpc': typeof ApiPublicMiniappRpcRoute
  '/api/public/oneid/start': typeof ApiPublicOneidStartRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/api/public/miniapp/lab'
    | '/api/public/miniapp/profile'
    | '/api/public/miniapp/rpc'
    | '/api/public/oneid/start'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/api/public/miniapp/lab'
    | '/api/public/miniapp/profile'
    | '/api/public/miniapp/rpc'
    | '/api/public/oneid/start'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/api/public/miniapp/lab'
    | '/api/public/miniapp/profile'
    | '/api/public/miniapp/rpc'
    | '/api/public/oneid/start'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  ApiPublicMiniappLabRoute: typeof ApiPublicMiniappLabRoute
  ApiPublicMiniappProfileRoute: typeof ApiPublicMiniappProfileRoute
  ApiPublicMiniappRpcRoute: typeof ApiPublicMiniappRpcRoute
  ApiPublicOneidStartRoute: typeof ApiPublicOneidStartRoute
  ApiPublicTelegramSetupRoute: typeof ApiPublicTelegramSetupRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/miniapp/lab': {
      id: '/api/public/miniapp/lab'
      path: '/api/public/miniapp/lab'
      fullPath: '/api/public/miniapp/lab'
      preLoaderRoute: typeof ApiPublicMiniappLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/miniapp/profile': {
      id: '/api/public/miniapp/profile'
      path: '/api/public/miniapp/profile'
      fullPath: '/api/public/miniapp/profile'
      preLoaderRoute: typeof ApiPublicMiniappProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/miniapp/rpc': {
      id: '/api/public/miniapp/rpc'
      path: '/api/public/miniapp/rpc'
      fullPath: '/api/public/miniapp/rpc'
      preLoaderRoute: typeof ApiPublicMiniappRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oneid/start': {
      id: '/api/public/oneid/start'
      path: '/api/public/oneid/start'
      fullPath: '/api/public/oneid/start'
      preLoaderRoute: typeof ApiPublicOneidStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/setup': {
      id: '/api/public/telegram/setup'
      path: '/api/public/telegram/setup'
      fullPath: '/api/public/telegram/setup'
      preLoaderRoute: typeof ApiPublicTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  ApiPublicMiniappLabRoute: ApiPublicMiniappLabRoute,
  ApiPublicMiniappProfileRoute: ApiPublicMiniappProfileRoute,
  ApiPublicMiniappRpcRoute: ApiPublicMiniappRpcRoute,
  ApiPublicOneidStartRoute: ApiPublicOneidStartRoute,
  ApiPublicTelegramSetupRoute: ApiPublicTelegramSetupRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
